// MASTER FILE FOR ALL APPLICATION ACTIONS

export const FETCH_SMURFS_START = 'FETCH_SMURFS_START';
export const FETCH_SMURFS_FINISH = 'FETCH_SMURFS_FINISH';

export const POST_SMURFS_START = 'FETCH_SMURFS_START';
export const POST_SMURFS_FINISH = 'FETCH_SMURFS_FINISH';


export const FETCH_SMURFS_RECEIVED = 'FETCH_SMURFS_RECEIVED';
export const FETCH_SMURFS_FAIL = 'FETCH_SMURFS_FAIL';

// export const TOGGLE_SET_FAVORITE ='TOGGLE_SET_FAVORITE';

// export const GENERIC_WAIT_START = 'GENERIC_WAIT_START';
// export const GENERIC_WAIT_FINISH = 'GENERIC_WAIT_FINISH';
