// MASTER FILE FOR ALL APPLICATION ACTIONS

export const FETCH_SMURFS_START = 'FETCH_SETS_START';
export const FETCH_SMURFS_FINISH = 'FETCH_SETS_FINISH';

export const FETCH_SMURFS_RECEIVED = 'FETCH_SETS_RECEIVED';
export const FETCH_SMURFS_FAIL = 'FETCH_SETS_FAIL';

// export const TOGGLE_SET_FAVORITE ='TOGGLE_SET_FAVORITE';

// export const GENERIC_WAIT_START = 'GENERIC_WAIT_START';
// export const GENERIC_WAIT_FINISH = 'GENERIC_WAIT_FINISH';
